imu_topic_freq: 100
gravity: 9.80665

useOdom: true
useVO: false
useTwist: false
camera_vo_topic: "pose"
odom_topic: "odom"
imu_topic: "/xbotcore/imu/imu_link"
twist_topic: "twist"



#TF from IMU to Base frame 
T_B_A: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 ,0, 1]
T_B_G: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 ,0, 1]

#Process Noise STDs
AccBiasSTDx:  0.000382554 #  m/s^2/sqrt(Hz)
AccBiasSTDy:  0.000382554
AccBiasSTDz:  0.000382554
GyroBiasSTDx: 8.67884e-06 
GyroBiasSTDy: 8.67884e-06 # rad/s/sqrt(Hz)
GyroBiasSTDz: 8.67884e-06
AccSTDx: 0.00119907 # 150 micro g/sqrt(Hz) -> m/s^2 
AccSTDy: 0.00119907
AccSTDz: 0.00119907
GyroSTDx: 0.00012 # 0.014deg/s/sqrt(Hz) -> rad/s/sqrt(Hz)
GyroSTDy: 0.00012
GyroSTDz: 0.00012
#Measurement Noise STDs
#If use Odom Update 
KinSTDx: 1.0e-04
KinSTDy: 1.0e-04
KinSTDz: 1.0e-04
KinSTDOrientx: 1.0e-02
KinSTDOrienty: 1.0e-02
KinSTDOrientz: 1.0e-02

#If use Twist Update
velSTDx: 1.0e-1
velSTDy: 1.0e-1
velSTDz: 1.0e-1

#If use VO update
VOSTDx: 1.0e-04
VOSTDy: 1.0e-04
VOSTDz: 1.0e-04
VOSTDOrientx: 1.0e-02
VOSTDOrienty: 1.0e-02
VOSTDOrientz: 1.0e-02

#IMU Initial Biases
biasAX:  0
biasAY: 0
biasAZ: 0
biasGX:  0
biasGY:  0
biasGZ:  0
calibrateIMUbiases: True
maxImuCalibrationCycles: 1000
#set only if calibrateIMUbiases is True
Mahony_Kp: 0.25
Mahony_Ki: 0